// server.js — FEthink Lesson Designer (Paid)
// COMPLETE FILE
// Includes:
// - /ask (AI generation)
// - /pptx (PowerPoint export)
// - Professional slide background
// - 24pt body text, 34pt titles
// - Optional logo data (from widget) embedded into PPTX

import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import OpenAI from "openai";
import crypto from "crypto";
import PptxGenJS from "pptxgenjs";

const app = express();
app.use(express.json({ limit: "2mb" }));

// -------------------- Paths --------------------
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PUBLIC_DIR = path.join(__dirname, "public");

// -------------------- OpenAI --------------------
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY
});

// -------------------- Config --------------------
const WIDGET_TOKEN_EXPLORER = process.env.WIDGET_TOKEN_EXPLORER;
const EXPLORER_DAILY_LIMIT = Number(process.env.EXPLORER_DAILY_LIMIT || 50);
const MAX_MESSAGE_CHARS = 8000;

// -------------------- Stores --------------------
const usage = new Map();

// -------------------- Helpers --------------------
function dayKey() {
  return new Date().toISOString().slice(0, 10);
}

function clientId(req) {
  const ip = req.headers["x-forwarded-for"] || req.socket.remoteAddress;
  const ua = req.headers["user-agent"] || "";
  return crypto.createHash("sha256").update(ip + ua).digest("hex").slice(0, 24);
}

function isSafeImageDataUrl(dataUrl) {
  if (!dataUrl || typeof dataUrl !== "string") return false;
  const okPrefix = /^data:image\/(png|jpeg|jpg|webp);base64,/i.test(dataUrl);
  if (!okPrefix) return false;
  // keep comfortably within JSON limits
  if (dataUrl.length > 900_000) return false;
  return true;
}

// -------------------- Static --------------------
app.use(express.static(PUBLIC_DIR, { extensions: ["html"] }));
app.get("/", (_, res) =>
  res.sendFile(path.join(PUBLIC_DIR, "widget-paid.html"))
);

// -------------------- PPTX helpers --------------------
function parseSlides(raw) {
  const lines = raw.split("\n");
  const slides = [];
  let current = null;

  for (const line of lines) {
    if (/^Slide\s+\d+/i.test(line)) {
      if (current) slides.push(current);
      current = { title: line.replace(/^Slide\s+\d+[:\-]?\s*/i, ""), bullets: [] };
    } else if (current && line.trim()) {
      current.bullets.push(line.replace(/^[-•*]\s*/, ""));
    }
  }
  if (current) slides.push(current);
  return slides.slice(0, 20);
}

async function buildPptx(slides, logoDataUrl = null) {
  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_WIDE";

  const BG = "F7F7F9";
  const ACCENT = "6F2DBD";
  const FONT = "Calibri";

  function addOptionalLogo(slide, opts = {}) {
    if (!logoDataUrl) return;
    try {
      // Wide slides are 13.333" x 7.5"
      const x = typeof opts.x === "number" ? opts.x : 11.6;
      const y = typeof opts.y === "number" ? opts.y : 0.55;
      const w = typeof opts.w === "number" ? opts.w : 1.5;
      const h = typeof opts.h === "number" ? opts.h : 0.85;
      slide.addImage({ data: logoDataUrl, x, y, w, h });
    } catch {
      // silently continue if logo cannot be embedded
    }
  }

  // ---- Title slide ----
  {
    const slide = pptx.addSlide();
    slide.background = { fill: BG };

    slide.addShape(pptx.ShapeType.rect, {
      x: 0, y: 0, w: "100%", h: 0.4, fill: ACCENT
    });

    addOptionalLogo(slide, { x: 10.9, y: 0.7, w: 2.0, h: 1.1 });

    slide.addText("FEthink – Lesson Slides", {
      x: 1, y: 2.2, w: 11, h: 1,
      fontFace: FONT, fontSize: 40, bold: true, color: "111111"
    });

    slide.addText("Generated by FEthink Lesson Designer", {
      x: 1, y: 3.4, w: 11,
      fontFace: FONT, fontSize: 16, color: "555555"
    });
  }

  // ---- Content slides ----
  slides.forEach(sl => {
    const slide = pptx.addSlide();
    slide.background = { fill: BG };

    slide.addShape(pptx.ShapeType.rect, {
      x: 0, y: 0, w: "100%", h: 0.35, fill: ACCENT
    });

    addOptionalLogo(slide, { x: 11.6, y: 0.55, w: 1.5, h: 0.85 });

    slide.addText(sl.title || "Slide", {
      x: 0.8, y: 0.6, w: 10.6, h: 0.9,
      fontFace: FONT, fontSize: 34, bold: true, color: "111111"
    });

    slide.addText(
      sl.bullets.map(b => `• ${b}`).join("\n"),
      {
        x: 1.1, y: 1.7, w: 10.8, h: 4.8,
        fontFace: FONT, fontSize: 24, color: "111111",
        valign: "top"
      }
    );
  });

  return pptx.write("nodebuffer");
}

// -------------------- /ask --------------------
app.post("/ask", async (req, res) => {
  try {
    const { message, tier, token } = req.body;
    if (!message || message.length > MAX_MESSAGE_CHARS)
      return res.json({ reply: "Invalid request." });

    if (tier === "explorer" && token !== WIDGET_TOKEN_EXPLORER)
      return res.json({ reply: "Access check failed." });

    const id = clientId(req);
    const key = `${dayKey()}::${id}`;
    const used = usage.get(key) || 0;

    if (used >= EXPLORER_DAILY_LIMIT)
      return res.json({ reply: "Daily limit reached.", used, limit: EXPLORER_DAILY_LIMIT });

    usage.set(key, used + 1);

    const ai = await openai.responses.create({
      model: "gpt-4o-mini",
      input: message
    });

    res.json({
      reply: ai.output_text,
      used: used + 1,
      limit: EXPLORER_DAILY_LIMIT
    });
  } catch {
    res.status(500).json({ reply: "AI error." });
  }
});

// -------------------- /pptx --------------------
app.post("/pptx", async (req, res) => {
  try {
    const { slidesText, tier, token, logoData } = req.body;

    if (tier === "explorer" && token !== WIDGET_TOKEN_EXPLORER)
      return res.status(403).json({ error: "Access denied" });

    const slides = parseSlides(slidesText);
    if (!slides.length)
      return res.status(400).json({ error: "No slides detected" });

    const logoDataUrl = isSafeImageDataUrl(logoData) ? logoData : null;
    const buffer = await buildPptx(slides, logoDataUrl);

    res.setHeader(
      "Content-Type",
      "application/vnd.openxmlformats-officedocument.presentationml.presentation"
    );
    res.setHeader(
      "Content-Disposition",
      'attachment; filename="FEthink-slides.pptx"'
    );

    res.send(buffer);
  } catch {
    res.status(500).json({ error: "PPT generation failed" });
  }
});

// -------------------- Start --------------------
const PORT = process.env.PORT || 10000;
app.listen(PORT, () =>
  console.log(`FEthink server running on port ${PORT}`)
);
